export const ROUTES = {
  ROOT: "/",
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    CALLBACK: "/auth/callback",
  },
  CANDIDATE: "/candidate",
  CANDIDATE_JOBS: "/candidate/jobs",
  CANDIDATE_APPLICATIONS: "/candidate/applications",
  CANDIDATE_APPLICATION_DETAIL: (id: string) => `/candidate/applications/${id}`,
  CANDIDATE_PROFILE: "/candidate/profile",
  CANDIDATE_MESSAGES: "/candidate/messages",
  CANDIDATE_DOCUMENTS: "/candidate/documents",
  RECRUITER: "/recruiter",
  RECRUITER_JOBS: "/recruiter/jobs",
  RECRUITER_JOB_PIPELINE: (id: string) => `/recruiter/jobs/${id}/pipeline`,
  RECRUITER_ORGANIZATION: "/recruiter/organization",
  RECRUITER_CANDIDATES: "/recruiter/candidates",
  RECRUITER_CANDIDATE_DETAIL: (jobId: string, applicationId: string) =>
    `/recruiter/candidates/${jobId}/${applicationId}`,
  RECRUITER_ANALYTICS: "/recruiter/analytics",
  RECRUITER_BIAS_REPORT: "/recruiter/bias-report",
  RECRUITER_MESSAGES: "/recruiter/messages",
  RECRUITER_INTERVIEWS: "/recruiter/interviews",
  CANDIDATE_INTERVIEWS: "/candidate/interviews",
  UNAUTHORIZED: "/unauthorized",
} as const;
