@baseUrl = http://localhost:5050
@contentType = application/json

# After login/register, paste the returned tokens here
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOWFlOWZiZS04MDU1LTQyNjgtYWY3Ny0yMGFiOTk2M2NmMzciLCJlbWFpbCI6InVkdWxhOTBAb3V0bG9vay5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJjYW5kaWRhdGUiLCJmaXJzdE5hbWUiOiJVZHVsYSIsImp0aSI6IjI0MTA4NmI0LWMwYTktNDQ1OS04MGVhLWI5NWMxOWYxMzU5MSIsImV4cCI6MTc3NTA0MDYzOSwiaXNzIjoidmV0dGx5LWF1dGgtc2VydmljZSIsImF1ZCI6InZldHRseS1wbGF0Zm9ybSJ9.IAACtQsEldBcz__Ca-phq6rb8vmmhxOYIVOf4oFqBaM
    
@refreshToken = 0p7Ay0oIvOJLAKNi/xnVVzfV8tpDSd3sFFVfF+UTw3AaBRgl+EsoM/MM3h5pqgO7Qf5cAqqXXxK1NnAKGh/vDQ==
@userId = d9ae9fbe-8055-4268-af77-20ab9963cf37

### Register
POST {{baseUrl}}/api/auth/register
Content-Type: {{contentType}}

{
  "email": "udula90@outlook.com",
  "password": "Abcd_1234",
  "role": "candidate",
  "firstName": "Udula",
  "lastName": "Thathsaridu"
}

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "udula90@outlook.com",
  "password": "Abcd_1234"
}

### Refresh Token
POST {{baseUrl}}/api/auth/refresh
Content-Type: {{contentType}}

{
  "userId": "{{userId}}",
  "refreshToken": "{{refreshToken}}"
}

### Logout
POST {{baseUrl}}/api/auth/logout
Authorization: Bearer {{accessToken}}

### Me (get current user)
GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{accessToken}}
